export const PAGE_ROUTE_NAME_MARKET = ''
export const PAGE_ROUTE_NAME_INVENTORY = 'inventory'
export const PAGE_ROUTE_NAME_PRODUCTS = 'products'
export const PAGE_ROUTE_NAME_LOCATIONS = 'locations'
export const PAGE_ROUTE_NAME_MOVING_ENTITIES = 'moving-entities'
export const PAGE_ROUTE_NAME_MAP = 'map'
export const PAGE_ROUTE_NAME_HISTORY = 'history'
